# Site settings
title: Luiti - An offline task management framework.
email: moc.liamg@emojvm
description: > # this means to ignore newlines until "baseurl:"
  An offline task management framework, built on top of luigi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luiti.github.io" # the base hostname & protocol for your site
twitter_username: mvj3
github_username:  luiti

# Build settings
markdown: kramdown
