# Site settings
project_name: Luiti
title: Luiti - An offline task management framework.
email: moc.liamg@emojvm
description: > # this means to ignore newlines until "baseurl:"
  An offline task management framework, built on top of luigi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luiti.github.io" # the base hostname & protocol for your site
twitter_username: mvj3
github_username:  luiti

github:
  repo: https://github.com/luiti/luiti
version: 0.2.1 # luiti version

# Dependencies
markdown:         redcarpet  # support 1. anchor 2. code highlight
redcarpet:  # ref from https://github.com/jekyll/jekyll/issues/1249
    extensions: [with_toc_data]
highlighter:      pygments


chinese_article:
  description: >
    前言 - 本文是《使用 Luiti 来构建数据仓库》 系列文章的其中一篇，面向的读者范围是对数据处理有一年以上经验的人。
    众所周知， Hadoop 和 新兴的 Spark 是当前最流行的分布式计算和存储平台，但是均和保守死板的 Java 编程语言所绑定。
    R 和 SQL 因为专业领域和表达能力的有限性而导致始终不能一统江湖。而 Python 作为一个通用的(胶水)脚本语言也拥有一个完
    全可以与 Java 匹敌的生态环境， 在 Web 开发，机器学习，文本挖掘，爬虫等方面均有众多优秀的框架和类库。

    本系列文章的侧重点在于从 Python 的函数式特征出发，来逐步讲解一个有约定而不失灵活性的离线数据仓库处理框架是怎么来的，
    和可以做什么。欢迎关注 http://luiti.github.io 。


